apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-generated-crio-add-inheritable-capabilities
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          compression: ""
          source: data:text/plain;charset=utf-8;base64,W2NyaW9dCiAgW2NyaW8ucnVudGltZV0KICAgIGFkZF9pbmhlcml0YWJsZV9jYXBhYmlsaXRpZXMgPSB0cnVlCg==
        mode: 420
        overwrite: true
        path: /etc/crio/crio.conf.d/01-mc-addInheritableCapabilities
  extensions: null
  fips: false
  kernelArguments: null
  kernelType: ""
  osImageURL: ""
